# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Shared/BigTeam/BigTeam/project/ETL Flight Delays")

# COMMAND ----------

df_flights   = spark.table("airport_delays.raw.apt_dly")
df_airports  = spark.table("airport_delays.raw.atc_pre_dep")
df_airlines  = spark.table("airport_delays.raw.enroute_dly")


# COMMAND ----------

df_flights.printSchema()
df_airports.printSchema()
df_airlines.printSchema()


# COMMAND ----------

df_flights.show(10, truncate=False)
df_airports.show(10, truncate=False)
df_airlines.show(10, truncate=False)


# COMMAND ----------

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

spark.sql("USE CATALOG airport_delays")
spark.sql("USE DATABASE raw")

# List all tables in your current catalog/database
tables = spark.catalog.listTables()

# Filter tables starting with silver_ or gold_
tables_to_drop = [t.name for t in tables if t.name.startswith("silver_") or t.name.startswith("gold_")]

# Drop themfrom pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

# Use the correct database
database_name = "raw"
spark.catalog.setCurrentDatabase(database_name)

# List all tables in the database
tables = spark.catalog.listTables(database_name)

# Filter tables starting with silver_ or gold_
tables_to_drop = [t.name for t in tables if t.name.startswith("silver_") or t.name.startswith("gold_")]

# Drop them
for table_name in tables_to_drop:
    fq_name = f"{database_name}.{table_name}"
    print(f"Dropping table: {fq_name}")
    spark.sql(f"DROP TABLE IF EXISTS {fq_name} PURGE")

for table_name in tables_to_drop:
    print(f"Dropping table: {table_name}")
    spark.sql(f"DROP TABLE IF EXISTS airport_delays.{table_name} PURGE")


# COMMAND ----------

spark.sql("SHOW TABLES IN airport_delays.raw").show()


# COMMAND ----------


